#!/usr/bin/env python3
"""Export the architecture-only PRP-R model as a compact C++ header."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def arguments() -> argparse.Namespace:
    root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", type=Path, default=root / "analysis" / "prpr" / "prpr_model.json")
    parser.add_argument("--out", type=Path, default=root / "include" / "prpr_model_data.hpp")
    return parser.parse_args()


def write_numbers(stream, ctype: str, name: str, values, per_line: int = 16) -> None:
    values = list(values)
    stream.write(f"inline constexpr {ctype} {name}[{len(values)}] = {{\n")
    for start in range(0, len(values), per_line):
        stream.write("    " + ", ".join(str(int(v)) for v in values[start : start + per_line]) + ",\n")
    stream.write("};\n\n")


def flatten(rows):
    offsets = [0]
    values = []
    for row in rows:
        values.extend(row)
        offsets.append(len(values))
    return offsets, values


def cpp_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def main() -> int:
    opt = arguments()
    model = json.loads(opt.model.read_text(encoding="utf-8"))
    direct_offsets, direct_values = flatten(model["direct_arcs"])
    target_offsets, target_values = flatten(model["target_arcs"])

    width, height = int(model["width"]), int(model["height"])
    vertical = {
        int(row["site"]): int(row["delay"])
        for row in model["gaps"]
        if row["direction"] == "vertical"
    }
    horizontal = {
        int(row["site"]): int(row["delay"])
        for row in model["gaps"]
        if row["direction"] == "horizontal"
    }
    x_prefix, y_prefix = [], []
    running = 0
    for x in range(width):
        x_prefix.append(running)
        running += vertical.get(x, 0)
    running = 0
    for y in range(height):
        y_prefix.append(running)
        running += horizontal.get(y, 0)

    sorted_ports = sorted((name, pid) for pid, name in enumerate(model["port_names"]))
    opt.out.parent.mkdir(parents=True, exist_ok=True)
    with opt.out.open("w", encoding="utf-8", newline="\n") as out:
        out.write("// Generated by tools/export_cpp_model.py. Do not edit.\n")
        out.write("#pragma once\n\n#include <cstdint>\n\nnamespace prpr_data {\n\n")
        out.write(f"inline constexpr int kPortCount = {len(model['port_names'])};\n")
        out.write(f"inline constexpr int kInputCount = {len(model['input_ports'])};\n")
        out.write(f"inline constexpr int kStateCount = {len(model['state_to_input'])};\n")
        out.write("inline constexpr int kClassCount = 16;\n")
        out.write(f"inline constexpr int kPrimitiveCount = {len(model['runtime_primitives'])};\n\n")
        out.write("struct OutputNet { int16_t state; int8_t dx; int8_t dy; };\n")
        out.write("struct PortCost { uint16_t id; uint16_t cost; };\n")
        out.write("struct Connector { int16_t dx; int16_t dy; uint16_t cost; };\n")
        out.write("struct Primitive { uint16_t id; uint8_t entry_class; uint8_t direction; int16_t dx; int16_t dy; uint16_t cost; };\n\n")
        out.write("inline constexpr const char* kSortedPortNames[kPortCount] = {\n")
        for name, _ in sorted_ports:
            out.write(f"    {cpp_string(name)},\n")
        out.write("};\n\n")
        write_numbers(out, "uint16_t", "kSortedPortIds", (pid for _, pid in sorted_ports))
        write_numbers(out, "int16_t", "kPortToInput", model["port_to_input"])
        write_numbers(out, "int16_t", "kInputToState", model["input_to_state"])
        write_numbers(out, "uint8_t", "kStateClass", model["state_classes"])

        out.write("inline constexpr OutputNet kOutputNet[kPortCount] = {\n")
        for state, dx, dy in model["output_nets"]:
            out.write(f"    {{{int(state)}, {int(dx)}, {int(dy)}}},\n")
        out.write("};\n\n")
        write_numbers(out, "uint16_t", "kDirectOffset", direct_offsets)
        out.write(f"inline constexpr PortCost kDirectArcs[{len(direct_values)}] = {{\n")
        for pid, cost in direct_values:
            out.write(f"    {{{int(pid)}, {int(cost)}}},\n")
        out.write("};\n\n")
        write_numbers(out, "uint16_t", "kTargetOffset", target_offsets)
        out.write(f"inline constexpr PortCost kTargetArcs[{len(target_values)}] = {{\n")
        for state, cost in target_values:
            out.write(f"    {{{int(state)}, {int(cost)}}},\n")
        out.write("};\n\n")

        out.write("inline constexpr Connector kConnector[kClassCount * kClassCount] = {\n")
        for source in range(16):
            for target in range(16):
                row = model["class_connectors"][source][target]
                out.write(f"    {{{int(row['dx'])}, {int(row['dy'])}, {int(row['cost'])}}},\n")
        out.write("};\n\n")
        out.write("inline constexpr Primitive kPrimitives[kPrimitiveCount] = {\n")
        for row in model["runtime_primitives"]:
            out.write(
                f"    {{{int(row['primitive_id'])}, {int(row['entry_class'])}, "
                f"{int(row['direction_bin'])}, {int(row['dx'])}, {int(row['dy'])}, "
                f"{int(row['total_delay'])}}},\n"
            )
        out.write("};\n\n")
        write_numbers(out, "uint16_t", "kXGapPrefix", x_prefix)
        write_numbers(out, "uint16_t", "kYGapPrefix", y_prefix)
        out.write("}  // namespace prpr_data\n")
    print(json.dumps({"out": str(opt.out.resolve()), "bytes": opt.out.stat().st_size}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
