#!/usr/bin/env python3
"""Quantize the selected exact-residual tables into a C++ header."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--ablation", type=Path, required=True)
    parser.add_argument("--tables", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    report = json.loads(args.ablation.read_text(encoding="utf-8"))
    best = report["best"]
    scale = 32768
    archive = np.load(args.tables)
    lines = [
        "// Generated by tools/export_exact_memory.py. Do not edit.",
        "#pragma once",
        "#include <cstdint>",
        "namespace v9_exact_memory {",
        f"inline constexpr float kScale = {1.0 / scale:.12g}f;",
    ]
    total = nonzero = 0
    for name in best["groups"]:
        values = np.asarray(archive[name], dtype=np.float64)
        quantized = np.rint(values * float(best["alpha"]) * scale).astype(np.int64)
        if quantized.min() < -32768 or quantized.max() > 32767:
            raise ValueError(f"{name} exceeds int16 after quantization")
        symbol = "".join(part.title() for part in name.split("_"))
        lines.append(f"inline constexpr int16_t k{symbol}[{quantized.size}] = {{")
        flat = quantized.tolist()
        for start in range(0, len(flat), 24):
            lines.append("    " + ", ".join(str(value) for value in flat[start : start + 24]) + ",")
        lines.append("};")
        total += quantized.size
        nonzero += int(np.count_nonzero(quantized))
    lines.extend(("}  // namespace v9_exact_memory", ""))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")
    print(
        json.dumps(
            {
                "output": str(args.output),
                "groups": best["groups"],
                "alpha": best["alpha"],
                "parameters": total,
                "nonzero": nonzero,
                "header_bytes": args.output.stat().st_size,
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
